{% set name = "greenery" %}
{% set version = "3.3.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/greenery-{{ version }}.tar.gz
  sha256: 7818ba0a26c7d16c8be569fe10a00b7cb59f2456adc74118b26c1ff71dcf14b9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - greenery
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/qntm/greenery
  summary: Greenery allows manipulation of regular expressions as finite state machines
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - beenje
