{% set name = "greenery" %}
{% set version = "4.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/greenery-{{ version }}.tar.gz
  sha256: 0b93c765532b5085dd7da3eee30a397b193c0d57e6cd5dae2d343e63555c0e77

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - greenery
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/qntm/greenery
  summary: Greenery allows manipulation of regular expressions as finite state machines
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - beenje
