{% set name = "greenery" %}
{% set version = "4.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/greenery-{{ version }}.tar.gz
  sha256: 6221d5727d19b4f46fc794635aa00b3dbbab33ed7ff1d686a0011d9197a4b7a0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - greenery
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/qntm/greenery
  summary: Greenery allows manipulation of regular expressions as finite state machines
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - beenje
